---
version: 1

ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

build_arg_defaults:
    EE_BASE_IMAGE: quay.io/ansible/ansible-runner:stable-2.9-latest 
    #  builder_image:
    # name:  quay.io/ansible/ansible-builder:latest
